import 'package:bikesellapp/controller/all_brnd_dtils_contol/bajaj_contoller.dart';
import 'package:bikesellapp/controller/all_brnd_dtils_contol/hero_contoller.dart';
import 'package:bikesellapp/controller/all_brnd_dtils_contol/runner_controller.dart';
import 'package:bikesellapp/controller/all_brnd_dtils_contol/suzuki_controller.dart';
import 'package:bikesellapp/controller/all_brnd_dtils_contol/tvs_controller.dart';
import 'package:bikesellapp/controller/all_brnd_dtils_contol/walton_controller.dart';
import 'package:bikesellapp/controller/all_brnd_dtils_contol/yamha_controller.dart';
import 'package:bikesellapp/controller/brand_controller.dart';
import 'package:bikesellapp/controller/new_update_controller.dart';
import 'package:bikesellapp/controller/offer_controller.dart';
BrandController brandController = BrandController.instance;
UpdateController updateController = UpdateController.instance;
BajaController bajaController = BajaController.instance;
HrController heroController = HrController.instance;
RunnerController runnerController = RunnerController.instance;
SuzukiController suzukiController = SuzukiController.instance;
TvsController tvsController = TvsController.instance;
WaltonController waltonController = WaltonController.instance;
YamhaController yamhaController = YamhaController.instance;
OfferController offerController = OfferController.instance;
